input_space:
  x:
    lower: -5
    upper: 5.0
    distribution: uniform
  'y':
    lower: -5
    upper: 5.0
    distribution: uniform
output_parameters:
- himmelblau
- booth
objectives:
  double_constraint:
    booth:
    - - gt
      - 2
    - - lt
      - 4
  single_constraint:
    himmelblau:
    - lt
    - 3.0
  gaussian_constraint: {}
