input_parameters: 
  m0: ["LHE","MINPAR","entries","1","value"]
  m12: ["LHE","MINPAR","entries","2","value"]
  TanBeta: ["LHE","MINPAR","entries","3","value"]
  Azero: ["LHE","MINPAR","entries","5","value"]
  MuInput: ["LHE","EXTPAR","entries","11","value"]
  MuPInput: ["LHE","EXTPAR","entries","12","value"]
  BMuInput: ["LHE","EXTPAR","entries","13","value"]
  BMuPInput: ["LHE","EXTPAR","entries","14","value"]
output_parameters: 
  Mh(1): ["HB","Mh(1)"]
  Mh(2): ["HB","Mh(2)"]
  obsratio: ["HB","obsratio"]
  csq(tot): ["HS", "csq(tot)"]
objectives: 
  double_constraint: 
    Mh(1): [["gt", 90.4],['lt',100.4]] 
    Mh(2): [["gt", 120.0],['lt',130.4]] 
    mu_aa: [["gt", 0.18],["lt", 0.37]]
    mu_bb: [["gt", 0.06],["lt", 0.174]]
    mu_tautau: [["gt", 0.7],["lt", 1.7]]
  single_constraint: 
    obsratio: ["lt", 1.0]
    csq(tot): ["lt", 136.6]
mg5_script: 
  gghaa: "/scratch/mjad1g20/phebo/configs/mg5_scripts/blssm_pphaa_LHC13.txt"
  eehzzbb: '/scratch/mjad1g20/phebo/configs/mg5_scripts/blssm_eehzzbb_LEP.txt'
  gghtautau: '/scratch/mjad1g20/phebo/configs/mg5_scripts/blssm_pphtautau_LHC13.txt'