input_parameters: 
  m0: ["LHS","MINPAR","entries","1","value"]
  m12: ["LHS","MINPAR","entries","2","value"]
  TanBeta: ["LHS","MINPAR","entries","3","value"]
  Azero: ["LHS","MINPAR","entries","5","value"]
  MuInput: ["LHS","EXTPAR","entries","11","value"]
  MuPInput: ["LHS","EXTPAR","entries","12","value"]
  BMuInput: ["LHS","EXTPAR","entries","13","value"]
  BMuPInput: ["LHS","EXTPAR","entries","14","value"]
output_parameters: 
  Mh(1): ["HB","Mh(1)"]
  Mh(2): ["HB","Mh(2)"]
  obsratio: ["HB","obsratio"]
  csq(tot): ["HS", "csq(tot)"]

objectives: 
  double_constraint: 
    mu_aa: [["gt", 0.18],["lt", 0.37]]
    Mh(1): [["gt", 90.4],['lt',100.4]] 
    Mh(2): [["gt", 120.0],['lt',130.4]] 
  single_constraint: 
    obsratio: ["lt", 1.0]
    csq(tot): ["lt", 136.6]
  #gaussian_constraint: 
